name = "base"
description = "Lorem Ipsum Dolor"
homepage = "https://github.com/tanjirantu"
tags = ["blog", "responsive", "google analytics", "disqus", "google search", "bootstrap", "fast", "social media share", "code", "math equations", "seo", "mermaid diagrams", "tech"]
min_version = "0.91.2"

[author]
  name = "Tanjir Antu"
  homepage = "https://github.com/tanjirantu/"